#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Autobot.Droid.Resource", IsApplication=true)]

namespace Autobot.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::Autobot.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::Autobot.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::Autobot.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::Autobot.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::Autobot.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::Autobot.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::Autobot.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::Autobot.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::Autobot.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::Autobot.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::Autobot.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::Autobot.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::Autobot.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::Autobot.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::Autobot.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Autobot.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::Autobot.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::Autobot.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::Autobot.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Autobot.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::Autobot.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::Autobot.Droid.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::Autobot.Droid.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::Autobot.Droid.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::Autobot.Droid.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::Autobot.Droid.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::Autobot.Droid.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::Autobot.Droid.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::Autobot.Droid.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::Autobot.Droid.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::Autobot.Droid.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::Autobot.Droid.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::Autobot.Droid.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::Autobot.Droid.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::Autobot.Droid.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.mini = global::Autobot.Droid.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::Autobot.Droid.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::Autobot.Droid.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::Autobot.Droid.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::Autobot.Droid.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::Autobot.Droid.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::Autobot.Droid.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::Autobot.Droid.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::Autobot.Droid.Resource.Styleable.FloatingActionButton_fab_size;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010011
			public const int MvxBind = 2130771985;
			
			// aapt resource value: 0x7f010015
			public const int MvxDropDownItemTemplate = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int MvxGroupItemTemplate = 2130771990;
			
			// aapt resource value: 0x7f010014
			public const int MvxItemTemplate = 2130771988;
			
			// aapt resource value: 0x7f010012
			public const int MvxLang = 2130771986;
			
			// aapt resource value: 0x7f010017
			public const int MvxSource = 2130771991;
			
			// aapt resource value: 0x7f010013
			public const int MvxTemplate = 2130771987;
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			// aapt resource value: 0x7f01000d
			public const int fab_colorDisabled = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int fab_colorNormal = 2130771980;
			
			// aapt resource value: 0x7f01000b
			public const int fab_colorPressed = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public const int fab_colorRipple = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int fab_shadow = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int fab_size = 2130771984;
			
			// aapt resource value: 0x7f010018
			public const int stiching = 2130771992;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050107
			public const int accent = 2131034375;
			
			// aapt resource value: 0x7f05009c
			public const int amber_100 = 2131034268;
			
			// aapt resource value: 0x7f05009d
			public const int amber_200 = 2131034269;
			
			// aapt resource value: 0x7f05009e
			public const int amber_300 = 2131034270;
			
			// aapt resource value: 0x7f05009f
			public const int amber_400 = 2131034271;
			
			// aapt resource value: 0x7f05009b
			public const int amber_50 = 2131034267;
			
			// aapt resource value: 0x7f0500a0
			public const int amber_500 = 2131034272;
			
			// aapt resource value: 0x7f0500a1
			public const int amber_600 = 2131034273;
			
			// aapt resource value: 0x7f0500a2
			public const int amber_700 = 2131034274;
			
			// aapt resource value: 0x7f0500a3
			public const int amber_800 = 2131034275;
			
			// aapt resource value: 0x7f0500a4
			public const int amber_900 = 2131034276;
			
			// aapt resource value: 0x7f0500a5
			public const int amber_A100 = 2131034277;
			
			// aapt resource value: 0x7f0500a6
			public const int amber_A200 = 2131034278;
			
			// aapt resource value: 0x7f0500a7
			public const int amber_A400 = 2131034279;
			
			// aapt resource value: 0x7f0500a8
			public const int amber_A700 = 2131034280;
			
			// aapt resource value: 0x7f050103
			public const int black = 2131034371;
			
			// aapt resource value: 0x7f0500c2
			public const int blue_100 = 2131034306;
			
			// aapt resource value: 0x7f0500c3
			public const int blue_200 = 2131034307;
			
			// aapt resource value: 0x7f0500c4
			public const int blue_300 = 2131034308;
			
			// aapt resource value: 0x7f0500c5
			public const int blue_400 = 2131034309;
			
			// aapt resource value: 0x7f0500c1
			public const int blue_50 = 2131034305;
			
			// aapt resource value: 0x7f0500c6
			public const int blue_500 = 2131034310;
			
			// aapt resource value: 0x7f0500c7
			public const int blue_600 = 2131034311;
			
			// aapt resource value: 0x7f0500c8
			public const int blue_700 = 2131034312;
			
			// aapt resource value: 0x7f0500c9
			public const int blue_800 = 2131034313;
			
			// aapt resource value: 0x7f0500ca
			public const int blue_900 = 2131034314;
			
			// aapt resource value: 0x7f0500cb
			public const int blue_A100 = 2131034315;
			
			// aapt resource value: 0x7f0500cc
			public const int blue_A200 = 2131034316;
			
			// aapt resource value: 0x7f0500cd
			public const int blue_A400 = 2131034317;
			
			// aapt resource value: 0x7f0500ce
			public const int blue_A700 = 2131034318;
			
			// aapt resource value: 0x7f05005a
			public const int blue_grey_100 = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int blue_grey_200 = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int blue_grey_300 = 2131034204;
			
			// aapt resource value: 0x7f05005d
			public const int blue_grey_400 = 2131034205;
			
			// aapt resource value: 0x7f050059
			public const int blue_grey_50 = 2131034201;
			
			// aapt resource value: 0x7f05005e
			public const int blue_grey_500 = 2131034206;
			
			// aapt resource value: 0x7f05005f
			public const int blue_grey_600 = 2131034207;
			
			// aapt resource value: 0x7f050060
			public const int blue_grey_700 = 2131034208;
			
			// aapt resource value: 0x7f050061
			public const int blue_grey_800 = 2131034209;
			
			// aapt resource value: 0x7f050062
			public const int blue_grey_900 = 2131034210;
			
			// aapt resource value: 0x7f0500aa
			public const int brown_100 = 2131034282;
			
			// aapt resource value: 0x7f0500ab
			public const int brown_200 = 2131034283;
			
			// aapt resource value: 0x7f0500ac
			public const int brown_300 = 2131034284;
			
			// aapt resource value: 0x7f0500ad
			public const int brown_400 = 2131034285;
			
			// aapt resource value: 0x7f0500a9
			public const int brown_50 = 2131034281;
			
			// aapt resource value: 0x7f0500ae
			public const int brown_500 = 2131034286;
			
			// aapt resource value: 0x7f0500af
			public const int brown_600 = 2131034287;
			
			// aapt resource value: 0x7f0500b0
			public const int brown_700 = 2131034288;
			
			// aapt resource value: 0x7f0500b1
			public const int brown_800 = 2131034289;
			
			// aapt resource value: 0x7f0500b2
			public const int brown_900 = 2131034290;
			
			// aapt resource value: 0x7f050000
			public const int cardview_dark_background = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_light_background = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_shadow_end_color = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int cardview_shadow_start_color = 2131034115;
			
			// aapt resource value: 0x7f050080
			public const int cyan_100 = 2131034240;
			
			// aapt resource value: 0x7f050081
			public const int cyan_200 = 2131034241;
			
			// aapt resource value: 0x7f050082
			public const int cyan_300 = 2131034242;
			
			// aapt resource value: 0x7f050083
			public const int cyan_400 = 2131034243;
			
			// aapt resource value: 0x7f05007f
			public const int cyan_50 = 2131034239;
			
			// aapt resource value: 0x7f050084
			public const int cyan_500 = 2131034244;
			
			// aapt resource value: 0x7f050085
			public const int cyan_600 = 2131034245;
			
			// aapt resource value: 0x7f050086
			public const int cyan_700 = 2131034246;
			
			// aapt resource value: 0x7f050087
			public const int cyan_800 = 2131034247;
			
			// aapt resource value: 0x7f050088
			public const int cyan_900 = 2131034248;
			
			// aapt resource value: 0x7f050089
			public const int cyan_A100 = 2131034249;
			
			// aapt resource value: 0x7f05008a
			public const int cyan_A200 = 2131034250;
			
			// aapt resource value: 0x7f05008b
			public const int cyan_A400 = 2131034251;
			
			// aapt resource value: 0x7f05008c
			public const int cyan_A700 = 2131034252;
			
			// aapt resource value: 0x7f05004c
			public const int deep_orange_100 = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int deep_orange_200 = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int deep_orange_300 = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int deep_orange_400 = 2131034191;
			
			// aapt resource value: 0x7f05004b
			public const int deep_orange_50 = 2131034187;
			
			// aapt resource value: 0x7f050050
			public const int deep_orange_500 = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int deep_orange_600 = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int deep_orange_700 = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int deep_orange_800 = 2131034195;
			
			// aapt resource value: 0x7f050054
			public const int deep_orange_900 = 2131034196;
			
			// aapt resource value: 0x7f050055
			public const int deep_orange_A100 = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int deep_orange_A200 = 2131034198;
			
			// aapt resource value: 0x7f050057
			public const int deep_orange_A400 = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int deep_orange_A700 = 2131034200;
			
			// aapt resource value: 0x7f050014
			public const int deep_purple_100 = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int deep_purple_200 = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int deep_purple_300 = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int deep_purple_400 = 2131034135;
			
			// aapt resource value: 0x7f050013
			public const int deep_purple_50 = 2131034131;
			
			// aapt resource value: 0x7f050018
			public const int deep_purple_500 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int deep_purple_600 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int deep_purple_700 = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int deep_purple_800 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int deep_purple_900 = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int deep_purple_A100 = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int deep_purple_A200 = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int deep_purple_A400 = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int deep_purple_A700 = 2131034144;
			
			// aapt resource value: 0x7f050004
			public const int fab_material_blue_500 = 2131034116;
			
			// aapt resource value: 0x7f050030
			public const int green_100 = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int green_200 = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int green_300 = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int green_400 = 2131034163;
			
			// aapt resource value: 0x7f05002f
			public const int green_50 = 2131034159;
			
			// aapt resource value: 0x7f050034
			public const int green_500 = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int green_600 = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int green_700 = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int green_800 = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int green_900 = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int green_A100 = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int green_A200 = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int green_A400 = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int green_A700 = 2131034172;
			
			// aapt resource value: 0x7f0500fa
			public const int grey_100 = 2131034362;
			
			// aapt resource value: 0x7f0500fb
			public const int grey_200 = 2131034363;
			
			// aapt resource value: 0x7f0500fc
			public const int grey_300 = 2131034364;
			
			// aapt resource value: 0x7f0500fd
			public const int grey_400 = 2131034365;
			
			// aapt resource value: 0x7f0500f9
			public const int grey_50 = 2131034361;
			
			// aapt resource value: 0x7f0500fe
			public const int grey_500 = 2131034366;
			
			// aapt resource value: 0x7f0500ff
			public const int grey_600 = 2131034367;
			
			// aapt resource value: 0x7f050100
			public const int grey_700 = 2131034368;
			
			// aapt resource value: 0x7f050101
			public const int grey_800 = 2131034369;
			
			// aapt resource value: 0x7f050102
			public const int grey_900 = 2131034370;
			
			// aapt resource value: 0x7f050072
			public const int indigo_100 = 2131034226;
			
			// aapt resource value: 0x7f050073
			public const int indigo_200 = 2131034227;
			
			// aapt resource value: 0x7f050074
			public const int indigo_300 = 2131034228;
			
			// aapt resource value: 0x7f050075
			public const int indigo_400 = 2131034229;
			
			// aapt resource value: 0x7f050071
			public const int indigo_50 = 2131034225;
			
			// aapt resource value: 0x7f050076
			public const int indigo_500 = 2131034230;
			
			// aapt resource value: 0x7f050077
			public const int indigo_600 = 2131034231;
			
			// aapt resource value: 0x7f050078
			public const int indigo_700 = 2131034232;
			
			// aapt resource value: 0x7f050079
			public const int indigo_800 = 2131034233;
			
			// aapt resource value: 0x7f05007a
			public const int indigo_900 = 2131034234;
			
			// aapt resource value: 0x7f05007b
			public const int indigo_A100 = 2131034235;
			
			// aapt resource value: 0x7f05007c
			public const int indigo_A200 = 2131034236;
			
			// aapt resource value: 0x7f05007d
			public const int indigo_A400 = 2131034237;
			
			// aapt resource value: 0x7f05007e
			public const int indigo_A700 = 2131034238;
			
			// aapt resource value: 0x7f050022
			public const int light_blue_100 = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int light_blue_200 = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int light_blue_300 = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int light_blue_400 = 2131034149;
			
			// aapt resource value: 0x7f050021
			public const int light_blue_50 = 2131034145;
			
			// aapt resource value: 0x7f050026
			public const int light_blue_500 = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int light_blue_600 = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int light_blue_700 = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int light_blue_800 = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int light_blue_900 = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int light_blue_A100 = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int light_blue_A200 = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int light_blue_A400 = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int light_blue_A700 = 2131034158;
			
			// aapt resource value: 0x7f05008e
			public const int light_green_100 = 2131034254;
			
			// aapt resource value: 0x7f05008f
			public const int light_green_200 = 2131034255;
			
			// aapt resource value: 0x7f050090
			public const int light_green_300 = 2131034256;
			
			// aapt resource value: 0x7f050091
			public const int light_green_400 = 2131034257;
			
			// aapt resource value: 0x7f05008d
			public const int light_green_50 = 2131034253;
			
			// aapt resource value: 0x7f050092
			public const int light_green_500 = 2131034258;
			
			// aapt resource value: 0x7f050093
			public const int light_green_600 = 2131034259;
			
			// aapt resource value: 0x7f050094
			public const int light_green_700 = 2131034260;
			
			// aapt resource value: 0x7f050095
			public const int light_green_800 = 2131034261;
			
			// aapt resource value: 0x7f050096
			public const int light_green_900 = 2131034262;
			
			// aapt resource value: 0x7f050097
			public const int light_green_A100 = 2131034263;
			
			// aapt resource value: 0x7f050098
			public const int light_green_A200 = 2131034264;
			
			// aapt resource value: 0x7f050099
			public const int light_green_A400 = 2131034265;
			
			// aapt resource value: 0x7f05009a
			public const int light_green_A700 = 2131034266;
			
			// aapt resource value: 0x7f0500de
			public const int lime_100 = 2131034334;
			
			// aapt resource value: 0x7f0500df
			public const int lime_200 = 2131034335;
			
			// aapt resource value: 0x7f0500e0
			public const int lime_300 = 2131034336;
			
			// aapt resource value: 0x7f0500e1
			public const int lime_400 = 2131034337;
			
			// aapt resource value: 0x7f0500dd
			public const int lime_50 = 2131034333;
			
			// aapt resource value: 0x7f0500e2
			public const int lime_500 = 2131034338;
			
			// aapt resource value: 0x7f0500e3
			public const int lime_600 = 2131034339;
			
			// aapt resource value: 0x7f0500e4
			public const int lime_700 = 2131034340;
			
			// aapt resource value: 0x7f0500e5
			public const int lime_800 = 2131034341;
			
			// aapt resource value: 0x7f0500e6
			public const int lime_900 = 2131034342;
			
			// aapt resource value: 0x7f0500e7
			public const int lime_A100 = 2131034343;
			
			// aapt resource value: 0x7f0500e8
			public const int lime_A200 = 2131034344;
			
			// aapt resource value: 0x7f0500e9
			public const int lime_A400 = 2131034345;
			
			// aapt resource value: 0x7f0500ea
			public const int lime_A700 = 2131034346;
			
			// aapt resource value: 0x7f0500ec
			public const int orange_100 = 2131034348;
			
			// aapt resource value: 0x7f0500ed
			public const int orange_200 = 2131034349;
			
			// aapt resource value: 0x7f0500ee
			public const int orange_300 = 2131034350;
			
			// aapt resource value: 0x7f0500ef
			public const int orange_400 = 2131034351;
			
			// aapt resource value: 0x7f0500eb
			public const int orange_50 = 2131034347;
			
			// aapt resource value: 0x7f0500f0
			public const int orange_500 = 2131034352;
			
			// aapt resource value: 0x7f0500f1
			public const int orange_600 = 2131034353;
			
			// aapt resource value: 0x7f0500f2
			public const int orange_700 = 2131034354;
			
			// aapt resource value: 0x7f0500f3
			public const int orange_800 = 2131034355;
			
			// aapt resource value: 0x7f0500f4
			public const int orange_900 = 2131034356;
			
			// aapt resource value: 0x7f0500f5
			public const int orange_A100 = 2131034357;
			
			// aapt resource value: 0x7f0500f6
			public const int orange_A200 = 2131034358;
			
			// aapt resource value: 0x7f0500f7
			public const int orange_A400 = 2131034359;
			
			// aapt resource value: 0x7f0500f8
			public const int orange_A700 = 2131034360;
			
			// aapt resource value: 0x7f050064
			public const int pink_100 = 2131034212;
			
			// aapt resource value: 0x7f050065
			public const int pink_200 = 2131034213;
			
			// aapt resource value: 0x7f050066
			public const int pink_300 = 2131034214;
			
			// aapt resource value: 0x7f050067
			public const int pink_400 = 2131034215;
			
			// aapt resource value: 0x7f050063
			public const int pink_50 = 2131034211;
			
			// aapt resource value: 0x7f050068
			public const int pink_500 = 2131034216;
			
			// aapt resource value: 0x7f050069
			public const int pink_600 = 2131034217;
			
			// aapt resource value: 0x7f05006a
			public const int pink_700 = 2131034218;
			
			// aapt resource value: 0x7f05006b
			public const int pink_800 = 2131034219;
			
			// aapt resource value: 0x7f05006c
			public const int pink_900 = 2131034220;
			
			// aapt resource value: 0x7f05006d
			public const int pink_A100 = 2131034221;
			
			// aapt resource value: 0x7f05006e
			public const int pink_A200 = 2131034222;
			
			// aapt resource value: 0x7f05006f
			public const int pink_A400 = 2131034223;
			
			// aapt resource value: 0x7f050070
			public const int pink_A700 = 2131034224;
			
			// aapt resource value: 0x7f050105
			public const int primary = 2131034373;
			
			// aapt resource value: 0x7f050106
			public const int primary_dark = 2131034374;
			
			// aapt resource value: 0x7f0500b4
			public const int purple_100 = 2131034292;
			
			// aapt resource value: 0x7f0500b5
			public const int purple_200 = 2131034293;
			
			// aapt resource value: 0x7f0500b6
			public const int purple_300 = 2131034294;
			
			// aapt resource value: 0x7f0500b7
			public const int purple_400 = 2131034295;
			
			// aapt resource value: 0x7f0500b3
			public const int purple_50 = 2131034291;
			
			// aapt resource value: 0x7f0500b8
			public const int purple_500 = 2131034296;
			
			// aapt resource value: 0x7f0500b9
			public const int purple_600 = 2131034297;
			
			// aapt resource value: 0x7f0500ba
			public const int purple_700 = 2131034298;
			
			// aapt resource value: 0x7f0500bb
			public const int purple_800 = 2131034299;
			
			// aapt resource value: 0x7f0500bc
			public const int purple_900 = 2131034300;
			
			// aapt resource value: 0x7f0500bd
			public const int purple_A100 = 2131034301;
			
			// aapt resource value: 0x7f0500be
			public const int purple_A200 = 2131034302;
			
			// aapt resource value: 0x7f0500bf
			public const int purple_A400 = 2131034303;
			
			// aapt resource value: 0x7f0500c0
			public const int purple_A700 = 2131034304;
			
			// aapt resource value: 0x7f050006
			public const int red_100 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int red_200 = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int red_300 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int red_400 = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int red_50 = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int red_500 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int red_600 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int red_700 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int red_800 = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int red_900 = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int red_A100 = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int red_A200 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int red_A400 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int red_A700 = 2131034130;
			
			// aapt resource value: 0x7f0500d0
			public const int teal_100 = 2131034320;
			
			// aapt resource value: 0x7f0500d1
			public const int teal_200 = 2131034321;
			
			// aapt resource value: 0x7f0500d2
			public const int teal_300 = 2131034322;
			
			// aapt resource value: 0x7f0500d3
			public const int teal_400 = 2131034323;
			
			// aapt resource value: 0x7f0500cf
			public const int teal_50 = 2131034319;
			
			// aapt resource value: 0x7f0500d4
			public const int teal_500 = 2131034324;
			
			// aapt resource value: 0x7f0500d5
			public const int teal_600 = 2131034325;
			
			// aapt resource value: 0x7f0500d6
			public const int teal_700 = 2131034326;
			
			// aapt resource value: 0x7f0500d7
			public const int teal_800 = 2131034327;
			
			// aapt resource value: 0x7f0500d8
			public const int teal_900 = 2131034328;
			
			// aapt resource value: 0x7f0500d9
			public const int teal_A100 = 2131034329;
			
			// aapt resource value: 0x7f0500da
			public const int teal_A200 = 2131034330;
			
			// aapt resource value: 0x7f0500db
			public const int teal_A400 = 2131034331;
			
			// aapt resource value: 0x7f0500dc
			public const int teal_A700 = 2131034332;
			
			// aapt resource value: 0x7f050104
			public const int white = 2131034372;
			
			// aapt resource value: 0x7f05003e
			public const int yellow_100 = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int yellow_200 = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int yellow_300 = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int yellow_400 = 2131034177;
			
			// aapt resource value: 0x7f05003d
			public const int yellow_50 = 2131034173;
			
			// aapt resource value: 0x7f050042
			public const int yellow_500 = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int yellow_600 = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int yellow_700 = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int yellow_800 = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int yellow_900 = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int yellow_A100 = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int yellow_A200 = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int yellow_A400 = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int yellow_A700 = 2131034186;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int cardview_compat_inset_shadow = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_default_elevation = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_default_radius = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int fab_elevation_lollipop = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int fab_scroll_threshold = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int fab_shadow_size = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int fab_size_mini = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int fab_size_normal = 2131099651;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int battery = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int battery_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int battery_okay = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bluetooth = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int circle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int display = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int fab_shadow = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int fab_shadow_mini = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int grid_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int grid_bg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int manual = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int place_holder = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int square = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int stitch = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int system = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int time = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int trigger = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int wifi = 2130837523;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int MvvmCrossTagId = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int MvxBindingTagUnique = 2131165185;
			
			// aapt resource value: 0x7f07000e
			public const int actionsListView = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int conditionsListView = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int fab = 2131165189;
			
			// aapt resource value: 0x7f070010
			public const int icon = 2131165200;
			
			// aapt resource value: 0x7f070007
			public const int linearLayout1 = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int mini = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int normal = 2131165187;
			
			// aapt resource value: 0x7f070006
			public const int promptList = 2131165190;
			
			// aapt resource value: 0x7f07000c
			public const int selectTriggerBtn = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int space1 = 2131165199;
			
			// aapt resource value: 0x7f070004
			public const int textView = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int textView1 = 2131165192;
			
			// aapt resource value: 0x7f07000a
			public const int textView2 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int textView3 = 2131165195;
			
			// aapt resource value: 0x7f070011
			public const int title = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int view1 = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int condition_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int HomeActivity = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int PromptGridDialogFragment = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int PromptListDialogFragment = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int rule_item = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RuleDetailActivity = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int SelectableGridItem = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SelectableListItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int ThemeButton = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int trigger_item = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080002
			public const int add_new_rule = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int app_name = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int hello = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040001
			public const int Base_CardView = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int CardView = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int CardView_Dark = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int CardView_Light = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Theme_Autobot = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int Theme_Autobot_ActionBar_TitleTextStyle = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int Theme_Autobot_ActionBarStyle = 2130968581;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] ContentView = new int[] {
					2130771992};
			
			// aapt resource value: 0
			public const int ContentView_stiching = 0;
			
			public static int[] FloatingActionButton = new int[] {
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] MvxBinding = new int[] {
					2130771985,
					2130771986};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771987};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771990};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771991};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771988,
					2130771989};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
