#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Autobot.Droid.Resource", IsApplication=true)]

namespace Autobot.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::Autobot.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::Autobot.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::Autobot.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::Autobot.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::Autobot.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::Autobot.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::Autobot.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::Autobot.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::Autobot.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::Autobot.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::Autobot.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::Autobot.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::Autobot.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::Autobot.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::Autobot.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::Autobot.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::Autobot.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::Autobot.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::Autobot.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::Autobot.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::Autobot.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::Autobot.Droid.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::Autobot.Droid.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::Autobot.Droid.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::Autobot.Droid.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::Autobot.Droid.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::Autobot.Droid.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::Autobot.Droid.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::Autobot.Droid.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::Autobot.Droid.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::Autobot.Droid.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::Autobot.Droid.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::Autobot.Droid.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::Autobot.Droid.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::Autobot.Droid.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.mini = global::Autobot.Droid.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::Autobot.Droid.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::Autobot.Droid.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::Autobot.Droid.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::Autobot.Droid.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::Autobot.Droid.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::Autobot.Droid.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::Autobot.Droid.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::Autobot.Droid.Resource.Styleable.FloatingActionButton_fab_size;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010028
			public const int MvxBind = 2130772008;
			
			// aapt resource value: 0x7f01002c
			public const int MvxDropDownItemTemplate = 2130772012;
			
			// aapt resource value: 0x7f01002d
			public const int MvxGroupItemTemplate = 2130772013;
			
			// aapt resource value: 0x7f01002b
			public const int MvxItemTemplate = 2130772011;
			
			// aapt resource value: 0x7f010029
			public const int MvxLang = 2130772009;
			
			// aapt resource value: 0x7f01002e
			public const int MvxSource = 2130772014;
			
			// aapt resource value: 0x7f01002a
			public const int MvxTemplate = 2130772010;
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010014
			public const int buttonSize = 2130771988;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010017
			public const int cardBackgroundColor = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int cardCornerRadius = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int cardElevation = 2130771993;
			
			// aapt resource value: 0x7f01001a
			public const int cardMaxElevation = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public const int cardPreventCornerOverlap = 2130771996;
			
			// aapt resource value: 0x7f01001b
			public const int cardUseCompatPadding = 2130771995;
			
			// aapt resource value: 0x7f010013
			public const int circleCrop = 2130771987;
			
			// aapt resource value: 0x7f010015
			public const int colorScheme = 2130771989;
			
			// aapt resource value: 0x7f01001d
			public const int contentPadding = 2130771997;
			
			// aapt resource value: 0x7f010021
			public const int contentPaddingBottom = 2130772001;
			
			// aapt resource value: 0x7f01001e
			public const int contentPaddingLeft = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int contentPaddingRight = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int contentPaddingTop = 2130772000;
			
			// aapt resource value: 0x7f010024
			public const int fab_colorDisabled = 2130772004;
			
			// aapt resource value: 0x7f010023
			public const int fab_colorNormal = 2130772003;
			
			// aapt resource value: 0x7f010022
			public const int fab_colorPressed = 2130772002;
			
			// aapt resource value: 0x7f010025
			public const int fab_colorRipple = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int fab_shadow = 2130772006;
			
			// aapt resource value: 0x7f010027
			public const int fab_size = 2130772007;
			
			// aapt resource value: 0x7f010012
			public const int imageAspectRatio = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatioAdjust = 2130771985;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010016
			public const int scopeUris = 2130771990;
			
			// aapt resource value: 0x7f01002f
			public const int stiching = 2130772015;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060118
			public const int accent = 2131099928;
			
			// aapt resource value: 0x7f0600ad
			public const int amber_100 = 2131099821;
			
			// aapt resource value: 0x7f0600ae
			public const int amber_200 = 2131099822;
			
			// aapt resource value: 0x7f0600af
			public const int amber_300 = 2131099823;
			
			// aapt resource value: 0x7f0600b0
			public const int amber_400 = 2131099824;
			
			// aapt resource value: 0x7f0600ac
			public const int amber_50 = 2131099820;
			
			// aapt resource value: 0x7f0600b1
			public const int amber_500 = 2131099825;
			
			// aapt resource value: 0x7f0600b2
			public const int amber_600 = 2131099826;
			
			// aapt resource value: 0x7f0600b3
			public const int amber_700 = 2131099827;
			
			// aapt resource value: 0x7f0600b4
			public const int amber_800 = 2131099828;
			
			// aapt resource value: 0x7f0600b5
			public const int amber_900 = 2131099829;
			
			// aapt resource value: 0x7f0600b6
			public const int amber_A100 = 2131099830;
			
			// aapt resource value: 0x7f0600b7
			public const int amber_A200 = 2131099831;
			
			// aapt resource value: 0x7f0600b8
			public const int amber_A400 = 2131099832;
			
			// aapt resource value: 0x7f0600b9
			public const int amber_A700 = 2131099833;
			
			// aapt resource value: 0x7f060114
			public const int black = 2131099924;
			
			// aapt resource value: 0x7f0600d3
			public const int blue_100 = 2131099859;
			
			// aapt resource value: 0x7f0600d4
			public const int blue_200 = 2131099860;
			
			// aapt resource value: 0x7f0600d5
			public const int blue_300 = 2131099861;
			
			// aapt resource value: 0x7f0600d6
			public const int blue_400 = 2131099862;
			
			// aapt resource value: 0x7f0600d2
			public const int blue_50 = 2131099858;
			
			// aapt resource value: 0x7f0600d7
			public const int blue_500 = 2131099863;
			
			// aapt resource value: 0x7f0600d8
			public const int blue_600 = 2131099864;
			
			// aapt resource value: 0x7f0600d9
			public const int blue_700 = 2131099865;
			
			// aapt resource value: 0x7f0600da
			public const int blue_800 = 2131099866;
			
			// aapt resource value: 0x7f0600db
			public const int blue_900 = 2131099867;
			
			// aapt resource value: 0x7f0600dc
			public const int blue_A100 = 2131099868;
			
			// aapt resource value: 0x7f0600dd
			public const int blue_A200 = 2131099869;
			
			// aapt resource value: 0x7f0600de
			public const int blue_A400 = 2131099870;
			
			// aapt resource value: 0x7f0600df
			public const int blue_A700 = 2131099871;
			
			// aapt resource value: 0x7f06006b
			public const int blue_grey_100 = 2131099755;
			
			// aapt resource value: 0x7f06006c
			public const int blue_grey_200 = 2131099756;
			
			// aapt resource value: 0x7f06006d
			public const int blue_grey_300 = 2131099757;
			
			// aapt resource value: 0x7f06006e
			public const int blue_grey_400 = 2131099758;
			
			// aapt resource value: 0x7f06006a
			public const int blue_grey_50 = 2131099754;
			
			// aapt resource value: 0x7f06006f
			public const int blue_grey_500 = 2131099759;
			
			// aapt resource value: 0x7f060070
			public const int blue_grey_600 = 2131099760;
			
			// aapt resource value: 0x7f060071
			public const int blue_grey_700 = 2131099761;
			
			// aapt resource value: 0x7f060072
			public const int blue_grey_800 = 2131099762;
			
			// aapt resource value: 0x7f060073
			public const int blue_grey_900 = 2131099763;
			
			// aapt resource value: 0x7f0600bb
			public const int brown_100 = 2131099835;
			
			// aapt resource value: 0x7f0600bc
			public const int brown_200 = 2131099836;
			
			// aapt resource value: 0x7f0600bd
			public const int brown_300 = 2131099837;
			
			// aapt resource value: 0x7f0600be
			public const int brown_400 = 2131099838;
			
			// aapt resource value: 0x7f0600ba
			public const int brown_50 = 2131099834;
			
			// aapt resource value: 0x7f0600bf
			public const int brown_500 = 2131099839;
			
			// aapt resource value: 0x7f0600c0
			public const int brown_600 = 2131099840;
			
			// aapt resource value: 0x7f0600c1
			public const int brown_700 = 2131099841;
			
			// aapt resource value: 0x7f0600c2
			public const int brown_800 = 2131099842;
			
			// aapt resource value: 0x7f0600c3
			public const int brown_900 = 2131099843;
			
			// aapt resource value: 0x7f060011
			public const int cardview_dark_background = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int cardview_light_background = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int cardview_shadow_end_color = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int cardview_shadow_start_color = 2131099668;
			
			// aapt resource value: 0x7f060008
			public const int common_action_bar_splitter = 2131099656;
			
			// aapt resource value: 0x7f060119
			public const int common_google_signin_btn_text_dark = 2131099929;
			
			// aapt resource value: 0x7f060009
			public const int common_google_signin_btn_text_dark_default = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int common_google_signin_btn_text_dark_disabled = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int common_google_signin_btn_text_dark_focused = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int common_google_signin_btn_text_dark_pressed = 2131099658;
			
			// aapt resource value: 0x7f06011a
			public const int common_google_signin_btn_text_light = 2131099930;
			
			// aapt resource value: 0x7f06000d
			public const int common_google_signin_btn_text_light_default = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int common_google_signin_btn_text_light_disabled = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int common_google_signin_btn_text_light_focused = 2131099664;
			
			// aapt resource value: 0x7f06000e
			public const int common_google_signin_btn_text_light_pressed = 2131099662;
			
			// aapt resource value: 0x7f06011b
			public const int common_plus_signin_btn_text_dark = 2131099931;
			
			// aapt resource value: 0x7f060000
			public const int common_plus_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int common_plus_signin_btn_text_dark_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_plus_signin_btn_text_dark_focused = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int common_plus_signin_btn_text_dark_pressed = 2131099649;
			
			// aapt resource value: 0x7f06011c
			public const int common_plus_signin_btn_text_light = 2131099932;
			
			// aapt resource value: 0x7f060004
			public const int common_plus_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int common_plus_signin_btn_text_light_disabled = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_plus_signin_btn_text_light_focused = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int common_plus_signin_btn_text_light_pressed = 2131099653;
			
			// aapt resource value: 0x7f060091
			public const int cyan_100 = 2131099793;
			
			// aapt resource value: 0x7f060092
			public const int cyan_200 = 2131099794;
			
			// aapt resource value: 0x7f060093
			public const int cyan_300 = 2131099795;
			
			// aapt resource value: 0x7f060094
			public const int cyan_400 = 2131099796;
			
			// aapt resource value: 0x7f060090
			public const int cyan_50 = 2131099792;
			
			// aapt resource value: 0x7f060095
			public const int cyan_500 = 2131099797;
			
			// aapt resource value: 0x7f060096
			public const int cyan_600 = 2131099798;
			
			// aapt resource value: 0x7f060097
			public const int cyan_700 = 2131099799;
			
			// aapt resource value: 0x7f060098
			public const int cyan_800 = 2131099800;
			
			// aapt resource value: 0x7f060099
			public const int cyan_900 = 2131099801;
			
			// aapt resource value: 0x7f06009a
			public const int cyan_A100 = 2131099802;
			
			// aapt resource value: 0x7f06009b
			public const int cyan_A200 = 2131099803;
			
			// aapt resource value: 0x7f06009c
			public const int cyan_A400 = 2131099804;
			
			// aapt resource value: 0x7f06009d
			public const int cyan_A700 = 2131099805;
			
			// aapt resource value: 0x7f06005d
			public const int deep_orange_100 = 2131099741;
			
			// aapt resource value: 0x7f06005e
			public const int deep_orange_200 = 2131099742;
			
			// aapt resource value: 0x7f06005f
			public const int deep_orange_300 = 2131099743;
			
			// aapt resource value: 0x7f060060
			public const int deep_orange_400 = 2131099744;
			
			// aapt resource value: 0x7f06005c
			public const int deep_orange_50 = 2131099740;
			
			// aapt resource value: 0x7f060061
			public const int deep_orange_500 = 2131099745;
			
			// aapt resource value: 0x7f060062
			public const int deep_orange_600 = 2131099746;
			
			// aapt resource value: 0x7f060063
			public const int deep_orange_700 = 2131099747;
			
			// aapt resource value: 0x7f060064
			public const int deep_orange_800 = 2131099748;
			
			// aapt resource value: 0x7f060065
			public const int deep_orange_900 = 2131099749;
			
			// aapt resource value: 0x7f060066
			public const int deep_orange_A100 = 2131099750;
			
			// aapt resource value: 0x7f060067
			public const int deep_orange_A200 = 2131099751;
			
			// aapt resource value: 0x7f060068
			public const int deep_orange_A400 = 2131099752;
			
			// aapt resource value: 0x7f060069
			public const int deep_orange_A700 = 2131099753;
			
			// aapt resource value: 0x7f060025
			public const int deep_purple_100 = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int deep_purple_200 = 2131099686;
			
			// aapt resource value: 0x7f060027
			public const int deep_purple_300 = 2131099687;
			
			// aapt resource value: 0x7f060028
			public const int deep_purple_400 = 2131099688;
			
			// aapt resource value: 0x7f060024
			public const int deep_purple_50 = 2131099684;
			
			// aapt resource value: 0x7f060029
			public const int deep_purple_500 = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int deep_purple_600 = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int deep_purple_700 = 2131099691;
			
			// aapt resource value: 0x7f06002c
			public const int deep_purple_800 = 2131099692;
			
			// aapt resource value: 0x7f06002d
			public const int deep_purple_900 = 2131099693;
			
			// aapt resource value: 0x7f06002e
			public const int deep_purple_A100 = 2131099694;
			
			// aapt resource value: 0x7f06002f
			public const int deep_purple_A200 = 2131099695;
			
			// aapt resource value: 0x7f060030
			public const int deep_purple_A400 = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int deep_purple_A700 = 2131099697;
			
			// aapt resource value: 0x7f060015
			public const int fab_material_blue_500 = 2131099669;
			
			// aapt resource value: 0x7f060041
			public const int green_100 = 2131099713;
			
			// aapt resource value: 0x7f060042
			public const int green_200 = 2131099714;
			
			// aapt resource value: 0x7f060043
			public const int green_300 = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int green_400 = 2131099716;
			
			// aapt resource value: 0x7f060040
			public const int green_50 = 2131099712;
			
			// aapt resource value: 0x7f060045
			public const int green_500 = 2131099717;
			
			// aapt resource value: 0x7f060046
			public const int green_600 = 2131099718;
			
			// aapt resource value: 0x7f060047
			public const int green_700 = 2131099719;
			
			// aapt resource value: 0x7f060048
			public const int green_800 = 2131099720;
			
			// aapt resource value: 0x7f060049
			public const int green_900 = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int green_A100 = 2131099722;
			
			// aapt resource value: 0x7f06004b
			public const int green_A200 = 2131099723;
			
			// aapt resource value: 0x7f06004c
			public const int green_A400 = 2131099724;
			
			// aapt resource value: 0x7f06004d
			public const int green_A700 = 2131099725;
			
			// aapt resource value: 0x7f06010b
			public const int grey_100 = 2131099915;
			
			// aapt resource value: 0x7f06010c
			public const int grey_200 = 2131099916;
			
			// aapt resource value: 0x7f06010d
			public const int grey_300 = 2131099917;
			
			// aapt resource value: 0x7f06010e
			public const int grey_400 = 2131099918;
			
			// aapt resource value: 0x7f06010a
			public const int grey_50 = 2131099914;
			
			// aapt resource value: 0x7f06010f
			public const int grey_500 = 2131099919;
			
			// aapt resource value: 0x7f060110
			public const int grey_600 = 2131099920;
			
			// aapt resource value: 0x7f060111
			public const int grey_700 = 2131099921;
			
			// aapt resource value: 0x7f060112
			public const int grey_800 = 2131099922;
			
			// aapt resource value: 0x7f060113
			public const int grey_900 = 2131099923;
			
			// aapt resource value: 0x7f060083
			public const int indigo_100 = 2131099779;
			
			// aapt resource value: 0x7f060084
			public const int indigo_200 = 2131099780;
			
			// aapt resource value: 0x7f060085
			public const int indigo_300 = 2131099781;
			
			// aapt resource value: 0x7f060086
			public const int indigo_400 = 2131099782;
			
			// aapt resource value: 0x7f060082
			public const int indigo_50 = 2131099778;
			
			// aapt resource value: 0x7f060087
			public const int indigo_500 = 2131099783;
			
			// aapt resource value: 0x7f060088
			public const int indigo_600 = 2131099784;
			
			// aapt resource value: 0x7f060089
			public const int indigo_700 = 2131099785;
			
			// aapt resource value: 0x7f06008a
			public const int indigo_800 = 2131099786;
			
			// aapt resource value: 0x7f06008b
			public const int indigo_900 = 2131099787;
			
			// aapt resource value: 0x7f06008c
			public const int indigo_A100 = 2131099788;
			
			// aapt resource value: 0x7f06008d
			public const int indigo_A200 = 2131099789;
			
			// aapt resource value: 0x7f06008e
			public const int indigo_A400 = 2131099790;
			
			// aapt resource value: 0x7f06008f
			public const int indigo_A700 = 2131099791;
			
			// aapt resource value: 0x7f060033
			public const int light_blue_100 = 2131099699;
			
			// aapt resource value: 0x7f060034
			public const int light_blue_200 = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int light_blue_300 = 2131099701;
			
			// aapt resource value: 0x7f060036
			public const int light_blue_400 = 2131099702;
			
			// aapt resource value: 0x7f060032
			public const int light_blue_50 = 2131099698;
			
			// aapt resource value: 0x7f060037
			public const int light_blue_500 = 2131099703;
			
			// aapt resource value: 0x7f060038
			public const int light_blue_600 = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int light_blue_700 = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int light_blue_800 = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int light_blue_900 = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int light_blue_A100 = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int light_blue_A200 = 2131099709;
			
			// aapt resource value: 0x7f06003e
			public const int light_blue_A400 = 2131099710;
			
			// aapt resource value: 0x7f06003f
			public const int light_blue_A700 = 2131099711;
			
			// aapt resource value: 0x7f06009f
			public const int light_green_100 = 2131099807;
			
			// aapt resource value: 0x7f0600a0
			public const int light_green_200 = 2131099808;
			
			// aapt resource value: 0x7f0600a1
			public const int light_green_300 = 2131099809;
			
			// aapt resource value: 0x7f0600a2
			public const int light_green_400 = 2131099810;
			
			// aapt resource value: 0x7f06009e
			public const int light_green_50 = 2131099806;
			
			// aapt resource value: 0x7f0600a3
			public const int light_green_500 = 2131099811;
			
			// aapt resource value: 0x7f0600a4
			public const int light_green_600 = 2131099812;
			
			// aapt resource value: 0x7f0600a5
			public const int light_green_700 = 2131099813;
			
			// aapt resource value: 0x7f0600a6
			public const int light_green_800 = 2131099814;
			
			// aapt resource value: 0x7f0600a7
			public const int light_green_900 = 2131099815;
			
			// aapt resource value: 0x7f0600a8
			public const int light_green_A100 = 2131099816;
			
			// aapt resource value: 0x7f0600a9
			public const int light_green_A200 = 2131099817;
			
			// aapt resource value: 0x7f0600aa
			public const int light_green_A400 = 2131099818;
			
			// aapt resource value: 0x7f0600ab
			public const int light_green_A700 = 2131099819;
			
			// aapt resource value: 0x7f0600ef
			public const int lime_100 = 2131099887;
			
			// aapt resource value: 0x7f0600f0
			public const int lime_200 = 2131099888;
			
			// aapt resource value: 0x7f0600f1
			public const int lime_300 = 2131099889;
			
			// aapt resource value: 0x7f0600f2
			public const int lime_400 = 2131099890;
			
			// aapt resource value: 0x7f0600ee
			public const int lime_50 = 2131099886;
			
			// aapt resource value: 0x7f0600f3
			public const int lime_500 = 2131099891;
			
			// aapt resource value: 0x7f0600f4
			public const int lime_600 = 2131099892;
			
			// aapt resource value: 0x7f0600f5
			public const int lime_700 = 2131099893;
			
			// aapt resource value: 0x7f0600f6
			public const int lime_800 = 2131099894;
			
			// aapt resource value: 0x7f0600f7
			public const int lime_900 = 2131099895;
			
			// aapt resource value: 0x7f0600f8
			public const int lime_A100 = 2131099896;
			
			// aapt resource value: 0x7f0600f9
			public const int lime_A200 = 2131099897;
			
			// aapt resource value: 0x7f0600fa
			public const int lime_A400 = 2131099898;
			
			// aapt resource value: 0x7f0600fb
			public const int lime_A700 = 2131099899;
			
			// aapt resource value: 0x7f0600fd
			public const int orange_100 = 2131099901;
			
			// aapt resource value: 0x7f0600fe
			public const int orange_200 = 2131099902;
			
			// aapt resource value: 0x7f0600ff
			public const int orange_300 = 2131099903;
			
			// aapt resource value: 0x7f060100
			public const int orange_400 = 2131099904;
			
			// aapt resource value: 0x7f0600fc
			public const int orange_50 = 2131099900;
			
			// aapt resource value: 0x7f060101
			public const int orange_500 = 2131099905;
			
			// aapt resource value: 0x7f060102
			public const int orange_600 = 2131099906;
			
			// aapt resource value: 0x7f060103
			public const int orange_700 = 2131099907;
			
			// aapt resource value: 0x7f060104
			public const int orange_800 = 2131099908;
			
			// aapt resource value: 0x7f060105
			public const int orange_900 = 2131099909;
			
			// aapt resource value: 0x7f060106
			public const int orange_A100 = 2131099910;
			
			// aapt resource value: 0x7f060107
			public const int orange_A200 = 2131099911;
			
			// aapt resource value: 0x7f060108
			public const int orange_A400 = 2131099912;
			
			// aapt resource value: 0x7f060109
			public const int orange_A700 = 2131099913;
			
			// aapt resource value: 0x7f060075
			public const int pink_100 = 2131099765;
			
			// aapt resource value: 0x7f060076
			public const int pink_200 = 2131099766;
			
			// aapt resource value: 0x7f060077
			public const int pink_300 = 2131099767;
			
			// aapt resource value: 0x7f060078
			public const int pink_400 = 2131099768;
			
			// aapt resource value: 0x7f060074
			public const int pink_50 = 2131099764;
			
			// aapt resource value: 0x7f060079
			public const int pink_500 = 2131099769;
			
			// aapt resource value: 0x7f06007a
			public const int pink_600 = 2131099770;
			
			// aapt resource value: 0x7f06007b
			public const int pink_700 = 2131099771;
			
			// aapt resource value: 0x7f06007c
			public const int pink_800 = 2131099772;
			
			// aapt resource value: 0x7f06007d
			public const int pink_900 = 2131099773;
			
			// aapt resource value: 0x7f06007e
			public const int pink_A100 = 2131099774;
			
			// aapt resource value: 0x7f06007f
			public const int pink_A200 = 2131099775;
			
			// aapt resource value: 0x7f060080
			public const int pink_A400 = 2131099776;
			
			// aapt resource value: 0x7f060081
			public const int pink_A700 = 2131099777;
			
			// aapt resource value: 0x7f060116
			public const int primary = 2131099926;
			
			// aapt resource value: 0x7f060117
			public const int primary_dark = 2131099927;
			
			// aapt resource value: 0x7f0600c5
			public const int purple_100 = 2131099845;
			
			// aapt resource value: 0x7f0600c6
			public const int purple_200 = 2131099846;
			
			// aapt resource value: 0x7f0600c7
			public const int purple_300 = 2131099847;
			
			// aapt resource value: 0x7f0600c8
			public const int purple_400 = 2131099848;
			
			// aapt resource value: 0x7f0600c4
			public const int purple_50 = 2131099844;
			
			// aapt resource value: 0x7f0600c9
			public const int purple_500 = 2131099849;
			
			// aapt resource value: 0x7f0600ca
			public const int purple_600 = 2131099850;
			
			// aapt resource value: 0x7f0600cb
			public const int purple_700 = 2131099851;
			
			// aapt resource value: 0x7f0600cc
			public const int purple_800 = 2131099852;
			
			// aapt resource value: 0x7f0600cd
			public const int purple_900 = 2131099853;
			
			// aapt resource value: 0x7f0600ce
			public const int purple_A100 = 2131099854;
			
			// aapt resource value: 0x7f0600cf
			public const int purple_A200 = 2131099855;
			
			// aapt resource value: 0x7f0600d0
			public const int purple_A400 = 2131099856;
			
			// aapt resource value: 0x7f0600d1
			public const int purple_A700 = 2131099857;
			
			// aapt resource value: 0x7f060017
			public const int red_100 = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int red_200 = 2131099672;
			
			// aapt resource value: 0x7f060019
			public const int red_300 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int red_400 = 2131099674;
			
			// aapt resource value: 0x7f060016
			public const int red_50 = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int red_500 = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int red_600 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int red_700 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int red_800 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int red_900 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int red_A100 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int red_A200 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int red_A400 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int red_A700 = 2131099683;
			
			// aapt resource value: 0x7f0600e1
			public const int teal_100 = 2131099873;
			
			// aapt resource value: 0x7f0600e2
			public const int teal_200 = 2131099874;
			
			// aapt resource value: 0x7f0600e3
			public const int teal_300 = 2131099875;
			
			// aapt resource value: 0x7f0600e4
			public const int teal_400 = 2131099876;
			
			// aapt resource value: 0x7f0600e0
			public const int teal_50 = 2131099872;
			
			// aapt resource value: 0x7f0600e5
			public const int teal_500 = 2131099877;
			
			// aapt resource value: 0x7f0600e6
			public const int teal_600 = 2131099878;
			
			// aapt resource value: 0x7f0600e7
			public const int teal_700 = 2131099879;
			
			// aapt resource value: 0x7f0600e8
			public const int teal_800 = 2131099880;
			
			// aapt resource value: 0x7f0600e9
			public const int teal_900 = 2131099881;
			
			// aapt resource value: 0x7f0600ea
			public const int teal_A100 = 2131099882;
			
			// aapt resource value: 0x7f0600eb
			public const int teal_A200 = 2131099883;
			
			// aapt resource value: 0x7f0600ec
			public const int teal_A400 = 2131099884;
			
			// aapt resource value: 0x7f0600ed
			public const int teal_A700 = 2131099885;
			
			// aapt resource value: 0x7f060115
			public const int white = 2131099925;
			
			// aapt resource value: 0x7f06004f
			public const int yellow_100 = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int yellow_200 = 2131099728;
			
			// aapt resource value: 0x7f060051
			public const int yellow_300 = 2131099729;
			
			// aapt resource value: 0x7f060052
			public const int yellow_400 = 2131099730;
			
			// aapt resource value: 0x7f06004e
			public const int yellow_50 = 2131099726;
			
			// aapt resource value: 0x7f060053
			public const int yellow_500 = 2131099731;
			
			// aapt resource value: 0x7f060054
			public const int yellow_600 = 2131099732;
			
			// aapt resource value: 0x7f060055
			public const int yellow_700 = 2131099733;
			
			// aapt resource value: 0x7f060056
			public const int yellow_800 = 2131099734;
			
			// aapt resource value: 0x7f060057
			public const int yellow_900 = 2131099735;
			
			// aapt resource value: 0x7f060058
			public const int yellow_A100 = 2131099736;
			
			// aapt resource value: 0x7f060059
			public const int yellow_A200 = 2131099737;
			
			// aapt resource value: 0x7f06005a
			public const int yellow_A400 = 2131099738;
			
			// aapt resource value: 0x7f06005b
			public const int yellow_A700 = 2131099739;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int cardview_compat_inset_shadow = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int cardview_default_elevation = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int cardview_default_radius = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int fab_elevation_lollipop = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int fab_scroll_threshold = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int fab_shadow_size = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int fab_size_mini = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int fab_size_normal = 2131230723;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int battery = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int battery_full = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int battery_low = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int battery_okay = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bluetooth = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bluetooth_on = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int circle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_full_open_on_phone = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_dark = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_dark_disabled = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_dark_focused = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_dark_normal = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_dark_pressed = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_icon_light_disabled = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_icon_light_focused = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_icon_light_normal = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_icon_light_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_dark_disabled = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_dark_focused = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_dark_normal = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_dark_pressed = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_text_light_disabled = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_google_signin_btn_text_light_focused = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_google_signin_btn_text_light_normal = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_google_signin_btn_text_light_pressed = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_ic_googleplayservices = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_dark_focused = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_icon_dark_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_icon_light = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_icon_light_disabled = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_icon_light_focused = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_icon_light_normal = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_icon_light_pressed = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_dark_disabled = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_dark_focused = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_text_dark_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_text_dark_pressed = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_plus_signin_btn_text_light = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int common_plus_signin_btn_text_light_disabled = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int common_plus_signin_btn_text_light_focused = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int common_plus_signin_btn_text_light_normal = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int common_plus_signin_btn_text_light_pressed = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int discovery = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int display = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int dreaming_started = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int fab_shadow = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int fab_shadow_mini = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int grid_background = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int grid_bg = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int Icon = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int manual = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int place_holder = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int power_connected = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int power_not_charging = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int power_usb = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int power_wireless = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int screen_off = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int screen_on = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int square = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int stitch = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int system = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int time = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int trigger = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int wifi = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int wifi_disabled = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int wifi_enabled = 2130837577;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090000
			public const int MvvmCrossTagId = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int MvxBindingTagUnique = 2131296257;
			
			// aapt resource value: 0x7f09001e
			public const int actionsListView = 2131296286;
			
			// aapt resource value: 0x7f090007
			public const int adjust_height = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int adjust_width = 2131296264;
			
			// aapt resource value: 0x7f09000c
			public const int auto = 2131296268;
			
			// aapt resource value: 0x7f090014
			public const int button1 = 2131296276;
			
			// aapt resource value: 0x7f09001d
			public const int conditionsListView = 2131296285;
			
			// aapt resource value: 0x7f09000d
			public const int dark = 2131296269;
			
			// aapt resource value: 0x7f090012
			public const int editText1 = 2131296274;
			
			// aapt resource value: 0x7f090015
			public const int fab = 2131296277;
			
			// aapt resource value: 0x7f090002
			public const int hybrid = 2131296258;
			
			// aapt resource value: 0x7f090020
			public const int icon = 2131296288;
			
			// aapt resource value: 0x7f090009
			public const int icon_only = 2131296265;
			
			// aapt resource value: 0x7f09000e
			public const int light = 2131296270;
			
			// aapt resource value: 0x7f090017
			public const int linearLayout1 = 2131296279;
			
			// aapt resource value: 0x7f090011
			public const int map = 2131296273;
			
			// aapt resource value: 0x7f09000f
			public const int mini = 2131296271;
			
			// aapt resource value: 0x7f090003
			public const int none = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int normal = 2131296260;
			
			// aapt resource value: 0x7f090016
			public const int promptList = 2131296278;
			
			// aapt resource value: 0x7f090005
			public const int satellite = 2131296261;
			
			// aapt resource value: 0x7f090013
			public const int seekBar1 = 2131296275;
			
			// aapt resource value: 0x7f09001c
			public const int selectTriggerBtn = 2131296284;
			
			// aapt resource value: 0x7f09001f
			public const int space1 = 2131296287;
			
			// aapt resource value: 0x7f09000a
			public const int standard = 2131296266;
			
			// aapt resource value: 0x7f090006
			public const int terrain = 2131296262;
			
			// aapt resource value: 0x7f090010
			public const int textView = 2131296272;
			
			// aapt resource value: 0x7f090018
			public const int textView1 = 2131296280;
			
			// aapt resource value: 0x7f09001a
			public const int textView2 = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int textView3 = 2131296283;
			
			// aapt resource value: 0x7f090021
			public const int title = 2131296289;
			
			// aapt resource value: 0x7f090019
			public const int view1 = 2131296281;
			
			// aapt resource value: 0x7f09000b
			public const int wide = 2131296267;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f050000
			public const int google_play_services_version = 2131034112;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int condition_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int geofence_detail_fragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int geofence_list_activity = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int HomeActivity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int PromptGridDialogFragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int PromptListDialogFragment = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int rule_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int RuleDetailActivity = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SelectableGridItem = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SelectableListItem = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int ThemeButton = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int trigger_item = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040021
			public const int add_new_rule = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int app_name = 2130968608;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_api_unavailable_text = 2130968600;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_enable_button = 2130968586;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_enable_text = 2130968585;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_enable_title = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_button = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_install_text_phone = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_install_text_tablet = 2130968582;
			
			// aapt resource value: 0x7f040004
			public const int common_google_play_services_install_title = 2130968580;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_invalid_account_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_invalid_account_title = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int common_google_play_services_network_error_text = 2130968593;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_network_error_title = 2130968592;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_ticker = 2130968579;
			
			// aapt resource value: 0x7f04001c
			public const int common_google_play_services_restricted_profile_text = 2130968604;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_restricted_profile_title = 2130968603;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_sign_in_failed_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_sign_in_failed_title = 2130968601;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_unknown_issue = 2130968578;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_unsupported_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_unsupported_title = 2130968596;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_update_button = 2130968598;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_update_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_update_title = 2130968587;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_updating_text = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_updating_title = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_wear_update_text = 2130968589;
			
			// aapt resource value: 0x7f040017
			public const int common_open_on_phone = 2130968599;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int common_signin_button_text_long = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int hello = 2130968607;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int Base_CardView = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int CardView = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int CardView_Dark = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int CardView_Light = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int Theme_Autobot = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int Theme_Autobot_ActionBar_TitleTextStyle = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int Theme_Autobot_ActionBarStyle = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] ContentView = new int[] {
					2130772015};
			
			// aapt resource value: 0
			public const int ContentView_stiching = 0;
			
			public static int[] FloatingActionButton = new int[] {
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			public static int[] LoadingImageView = new int[] {
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] MvxBinding = new int[] {
					2130772008,
					2130772009};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130772010};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130772013};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130772014};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130772011,
					2130772012};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] SignInButton = new int[] {
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
